apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: app
  labels:
    app.kubernetes.io/name: server
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: server
    spec:
      containers:
      - name: server
        image: jackmead515/doggy_cam_server:alpha8
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 5
        ports:
          - containerPort: 8000
          - containerPort: 3131 
            protocol: UDP
        env:
          - name: HTTP_PORT
            value: "8000"
          - name: FFMPEG_PIPELINE
            value: "ffmpeg"