apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: server
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30200
  - name: stream
    port: 3131
    targetPort: 3131
    protocol: UDP