apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  namespace: app
  labels:
    app.kubernetes.io/name: core
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: core
  template:
    metadata:
      labels:
        app.kubernetes.io/name: core
    spec:
      containers:
      - name: core
        image: jackmead515/doggy_cam_core:alpha6
        imagePullPolicy: IfNotPresent
        env:
          - name: KAFKA_BROKERS
            value: kafka-kafka-bootstrap.kafka.svc.cluster.local:9092