apiVersion: v1
kind: Service
metadata:
  name: core
  namespace: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: core
  ports:
  - name: stream
    port: 3131
    targetPort: 3131
    protocol: UDP