apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay
  namespace: app
  labels:
    app.kubernetes.io/name: relay
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: relay
  template:
    metadata:
      labels:
        app.kubernetes.io/name: relay
    spec:
      containers:
      - name: relay
        image: jackmead515/doggy_cam_relay:alpha6
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5454
        env:
          - name: NODE_ENV
            value: production
          - name: STREAM_HOST
            value: app.server.svc.cluster.local
          - name: STREAM_PORT
            value: "3131"
          - name: HTTP_PORT
            value: "5454"