apiVersion: v1
kind: Service
metadata:
  name: relay
  namespace: app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: relay
  ports:
  - name: http
    port: 5454
    targetPort: 5454
    nodePort: 30201